version: "3.3"
services: 
  api:
    container_name: api_container
    image: salimrashid/api-docker-image
    ports:
     - "8000:8000"
  frontend: 
    container_name: frontend_container
    image: salimrashid/frontend-docker-image
    ports: 
    - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - api 
