version: "3.8"
services: 
  frontend: 
    build: ./frontend
    container_name: frontend_container
    ports: 
    - "3000:3000"
    stdin_open: true
    tty: true
  api:
    build: ./api
    container_name: api_container
    ports:
     - "8000:8000"
